# SOAL 1

### Eliminasi Gauss untuk Dekomposisi LU

Metode ini mengubah matriks persegi ($A$) menjadi hasil kali dua matriks segitiga: matriks segitiga bawah ($L$) dan matriks segitiga atas ($U$), sehingga $A = LU$. Prosesnya menghasilkan $U$ melalui operasi baris, sementara faktor-faktor yang digunakan selama eliminasi disimpan untuk membentuk $L$.

Input:

* $A$: Matriks persegi $n \times n$.

Output:

* $L$: Matriks segitiga bawah $n \times n$.
* $U$: Matriks segitiga atas $n \times n$.

FUNGSI Dekomposisi_LU(A)
:                                                                                               
  n = jumlah_baris(A)                                                                                                       
  U = salinan_dari(A)          // U akan menjadi matriks segitiga atas                                                      
  L = matriks_identitas_ukuran(n) // L diinisialisasi sebagai matriks identitas

  UNTUK k DARI 0 SAMPAI n-2:     // Iterasi untuk setiap kolom (pivot)                                                      
    // Penanganan pivot nol: Jika U[k][k] adalah nol, sistem mungkin singular.                                                      
    // Implementasi yang lebih robust akan menyertakan pivoting (pertukaran baris).                                                             
    Jika U[k][k] == 0:                                                                                                      
      KEMBALIKAN Error "Pembagian oleh nol: Elemen pivot adalah nol."

    UNTUK i DARI k+1 SAMPAI n-1: // Iterasi untuk baris di bawah pivot saat ini
      faktor = U[i][k] / U[k][k]
      L[i][k] = faktor            // Simpan faktor pengali di matriks L
      UNTUK j DARI k SAMPAI n-1:  // Lakukan operasi eliminasi baris
        U[i][j] = U[i][j] - faktor * U[k][j]
  KEMBALIKAN L, U

### Eliminasi Gauss-Jordan
Metode ini adalah cara langsung untuk menyelesaikan sistem persamaan linear dengan $n$ variabel. Prosesnya melibatkan transformasi matriks koefisien ($A$) yang digabung dengan vektor konstanta ($b$) menjadi matriks yang diperbesar ($[A|b]$). Melalui serangkaian operasi baris, matriks ini diubah menjadi bentuk eselon baris tereduksi, di mana matriks koefisien menjadi matriks identitas. Solusi sistem akan langsung terbaca dari kolom konstanta yang telah dimodifikasi.

Input:

* $A$: Matriks koefisien $n \times n$.
* $b$: Vektor konstanta $n \times 1$.

Output:

* $x$: Vektor solusi $n \times 1$.

FUNGSI Selesaikan_Gauss_Jordan(A, b):                                                                                       
  n = jumlah_baris(A)                                                                                                                   
  Matriks_Augmentasi = gabungkan(A, b) // Membuat matriks n x (n+1)                                                                   

  UNTUK k DARI 0 SAMPAI n-1: // Iterasi untuk setiap kolom (pivot)                                                          
    // (Opsional) Pivoting: Cari baris dengan nilai absolut terbesar di kolom k saat ini                                            
    // dan tukar baris jika perlu untuk meningkatkan stabilitas numerik.

    // Normalisasi baris pivot: Membuat elemen pivot menjadi 1
    elemen_pivot = Matriks_Augmentasi[k][k]
    Jika elemen_pivot == 0:
      KEMBALIKAN Error "Pembagian oleh nol: Elemen pivot adalah nol. Sistem mungkin singular."

    UNTUK j DARI k SAMPAI n:
      Matriks_Augmentasi[k][j] = Matriks_Augmentasi[k][j] / elemen_pivot

    // Eliminasi baris lain: Membuat elemen di atas dan di bawah pivot menjadi nol
    UNTUK i DARI 0 SAMPAI n-1:
      JIKA i != k:
        faktor = Matriks_Augmentasi[i][k]
        UNTUK j DARI k SAMPAI n:
          Matriks_Augmentasi[i][j] = Matriks_Augmentasi[i][j] - faktor * Matriks_Augmentasi[k][j]

  // Ekstrak vektor solusi x dari kolom terakhir matriks augmentasi                                                         
  x = vektor_baru_ukuran(n)                                                                                                         
  UNTUK i DARI 0 SAMPAI n-1:                                                                                                    
    x[i] = Matriks_Augmentasi[i][n]

### Metode Iteratif Gauss-Seidel
Metode Gauss-Seidel adalah teknik iteratif untuk mencari solusi sistem persamaan linear. Dimulai dari tebakan awal, solusi diperbaiki secara bertahap pada setiap iterasi. Keunggulannya adalah penggunaan nilai variabel yang terbaru segera setelah dihitung dalam iterasi yang sama, yang seringkali mempercepat konvergensi. Metode ini bekerja optimal jika matriks koefisien dominan secara diagonal.

Input:

* $A$: Matriks koefisien $n \times n$.
* $b$: Vektor konstanta $n \times 1$.
* $tebakan_awal$: Vektor $n \times 1$ sebagai tebakan awal solusi.
* $maks_iterasi$: Jumlah maksimum iterasi yang diizinkan.
* $toleransi$: Ambang batas untuk kriteria konvergensi.

Output:

* $x$: Vektor solusi $n \times 1$ (jika konvergen).
* 'Tidak konvergen': Jika solusi tidak konvergen dalam batas $maks_iterasi$.

FUNGSI Selesaikan_Gauss_Seidel(A, b, tebakan_awal, maks_iterasi, toleransi):                                                
  n = jumlah_baris(A)                                                                                                       
  x = salinan_dari(tebakan_awal) // Inisialisasi solusi saat ini                                                                
  x_baru = vektor_baru_ukuran(n) // Untuk menyimpan nilai yang baru dihitung                                                        

  UNTUK iterasi DARI 1 SAMPAI maks_iterasi:                                                                                     
    error = 0.0 // Untuk melacak perubahan solusi pada iterasi ini

    UNTUK i DARI 0 SAMPAI n-1: // Hitung nilai baru untuk setiap komponen x[i]
      jumlah_nilai = 0.0
      UNTUK j DARI 0 SAMPAI n-1:
        JIKA j != i:
          jumlah_nilai = jumlah_nilai + A[i][j] * x[j] // Gunakan x[j] yang sudah diperbarui

      Jika A[i][i] == 0:
        KEMBALIKAN Error "Elemen diagonal A[i][i] adalah nol. Metode ini mungkin tidak konvergen."
      
      x_baru[i] = (b[i] - jumlah_nilai) / A[i][i]
      error = error + abs(x_baru[i] - x[i]) // Tambahkan selisih absolut ke total error

    x = salinan_dari(x_baru) // Perbarui x dengan nilai yang baru dihitung untuk iterasi berikutnya

    JIKA error < toleransi: // Periksa kriteria konvergensi
      KEMBALIKAN x // Solusi dianggap telah konvergen

  KEMBALIKAN 'Tidak konvergen dalam batas maks_iterasi' // Jika iterasi habis tapi belum konvergen







# SOAL 2

## **Analisis Arus pada Rangkaian Listrik DC Kompleks ⚡**

### **1. Definisi Masalah Fisika**

Dalam fisika, salah satu aplikasi paling umum dari sistem persamaan linear adalah analisis rangkaian listrik arus searah (DC). Dengan menggunakan **Hukum Kirchhoff**, kita dapat menentukan nilai arus yang mengalir di setiap cabang dari sebuah rangkaian yang kompleks.

**Problem:**
Diberikan sebuah rangkaian listrik DC yang terdiri dari dua sumber tegangan ($V_1$ dan $V_2$) dan tujuh buah resistor ($R_1$ hingga $R_7$). Kita ingin menentukan besar arus listrik yang mengalir pada setiap *loop* independen dalam rangkaian ($i_1, i_2, i_3, i_4$).

**Diagram Rangkaian:**
Bayangkan sebuah rangkaian dengan empat "kotak" atau loop yang saling terhubung.

* **Loop 1 (arus $i_1$):** Mengandung sumber tegangan $V_1$, resistor $R_1$, dan $R_2$.
* **Loop 2 (arus $i_2$):** Mengandung resistor $R_1$, $R_3$, dan $R_5$.
* **Loop 3 (arus $i_3$):** Mengandung resistor $R_2$, $R_4$, $R_6$ dan sumber tegangan $V_2$.
* **Loop 4 (arus $i_4$):** Mengandung resistor $R_5$, $R_6$, dan $R_7$.

**Nilai Komponen:**
* $V_1 = 20$ Volt
* $V_2 = 10$ Volt
* $R_1 = 2 \, \Omega$
* $R_2 = 3 \, \Omega$
* $R_3 = 4 \, \Omega$
* $R_4 = 2 \, \Omega$
* $R_5 = 5 \, \Omega$
* $R_6 = 3 \, \Omega$
* $R_7 = 6 \, \Omega$

---

### **2. Formulasi Masalah Matematis**

Kita akan menggunakan **Hukum II Kirchhoff (Hukum Tegangan Kirchhoff)**, yang menyatakan bahwa jumlah aljabar dari perubahan potensial (tegangan) yang ditemui dalam lintasan tertutup (loop) adalah nol ($\Sigma V = 0$).

Kita definisikan arah arus loop searah jarum jam untuk semua loop.

* **Analisis Loop 1:**
    $V_1 - R_1(i_1 - i_2) - R_2(i_1 - i_3) = 0$
    $20 - 2(i_1 - i_2) - 3(i_1 - i_3) = 0$
    $5i_1 - 2i_2 - 3i_3 + 0i_4 = 20$

* **Analisis Loop 2:**
    $-R_3(i_2) - R_5(i_2 - i_4) - R_1(i_2 - i_1) = 0$
    $-4i_2 - 5(i_2 - i_4) - 2(i_2 - i_1) = 0$
    $-2i_1 + 11i_2 + 0i_3 - 5i_4 = 0$

* **Analisis Loop 3:**
    $-R_4(i_3) - V_2 - R_6(i_3 - i_4) - R_2(i_3 - i_1) = 0$
    $-2i_3 - 10 - 3(i_3 - i_4) - 3(i_3 - i_1) = 0$
    $-3i_1 + 0i_2 + 8i_3 - 3i_4 = 10$

* **Analisis Loop 4:**
    $-R_7(i_4) - R_6(i_4 - i_3) - R_5(i_4 - i_2) = 0$
    $-6i_4 - 3(i_4 - i_3) - 5(i_4 - i_2) = 0$
    $0i_1 - 5i_2 - 3i_3 + 14i_4 = 0$

Sistem Persamaan Linear (SPL) ini dapat ditulis dalam bentuk matriks $Ax = b$:

$$
\begin{pmatrix}
5 & -2 & -3 & 0 \\
-2 & 11 & 0 & -5 \\
-3 & 0 & 8 & -3 \\
0 & -5 & -3 & 14
\end{pmatrix}
\begin{pmatrix}
i_1 \\ i_2 \\ i_3 \\ i_4
\end{pmatrix}
=
\begin{pmatrix}
20 \\ 0 \\ 10 \\ 0
\end{pmatrix}
$$

Di sini, $A$ adalah matriks koefisien, $x$ adalah vektor variabel arus yang ingin kita cari, dan $b$ adalah vektor konstanta.

---

### **3. Algoritma Metode Numerik: Eliminasi Gauss**

Metode Eliminasi Gauss adalah algoritma standar untuk menyelesaikan sistem persamaan linear $Ax=b$. Algoritma ini terdiri dari dua tahap utama:

1.  **Tahap Eliminasi Maju (Forward Elimination):**
    Tujuan dari tahap ini adalah untuk mengubah matriks koefisien $A$ menjadi matriks segitiga atas ($U$). Proses ini dilakukan dengan mengeliminasi variabel secara sistematis dari persamaan-persamaan di bawahnya.
    * Mulai dari kolom pertama (kolom $j=0$).
    * Untuk setiap baris $i$ di bawah baris pivot (baris $j$), hitung faktor pengali $m = A_{ij} / A_{jj}$.
    * Kurangkan baris $i$ dengan hasil perkalian faktor $m$ dan baris pivot $j$. Operasi ini juga diterapkan pada vektor $b$.
    * Ulangi proses ini untuk semua kolom hingga $n-1$, di mana $n$ adalah jumlah variabel.

2.  **Tahap Substitusi Mundur (Back Substitution):**
    Setelah matriks $A$ menjadi matriks segitiga atas $U$, kita dapat dengan mudah menemukan solusi dengan menghitungnya dari variabel terakhir ($x_n$) hingga variabel pertama ($x_1$).
    * Hitung variabel terakhir: $x_n = b_n / U_{nn}$.
    * Untuk variabel-variabel lainnya, hitung secara mundur ($i = n-1, n-2, ..., 1$):
        $$x_i = \frac{1}{U_{ii}} \left( b_i - \sum_{j=i+1}^{n} U_{ij}x_j \right)$$

---

### **4. Implementasi dan Solusi Pemrograman (Python)**

Berikut adalah implementasi dari metode Eliminasi Gauss menggunakan Python dan library `numpy` untuk kemudahan operasi matriks.

```python
import numpy as np

def eliminasi_gauss(A, b):
    """
    Menyelesaikan sistem persamaan linear Ax = b menggunakan metode Eliminasi Gauss.

    Args:
        A (np.array): Matriks koefisien (n x n).
        b (np.array): Vektor konstanta (n x 1).

    Returns:
        np.array: Vektor solusi x.
    """
    n = len(b)
    # Buat augmented matrix [A|b] untuk kemudahan operasi
    Ab = np.hstack([A.astype(float), b.reshape(-1, 1).astype(float)])
    print("Matriks Augmented Awal [A|b]:")
    print(Ab)
    print("\n--- Proses Eliminasi Maju ---\n")

    # 1. Tahap Eliminasi Maju
    for j in range(n):
        # Lakukan eliminasi untuk baris di bawah pivot
        for i in range(j + 1, n):
            faktor = Ab[i, j] / Ab[j, j]
            Ab[i, j:] = Ab[i, j:] - faktor * Ab[j, j:]
            print(f"Operasi Baris R{i+1} = R{i+1} - ({faktor:.4f}) * R{j+1}")
            print(Ab)
            print("-" * 30)

    # Pisahkan kembali menjadi matriks U dan vektor b'
    U = Ab[:, :n]
    b_prime = Ab[:, n]

    print("\nMatriks Segitiga Atas (U):")
    print(U)
    print("\nVektor b' hasil modifikasi:")
    print(b_prime)
    print("\n--- Proses Substitusi Mundur ---\n")
    
    # 2. Tahap Substitusi Mundur
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        # Hitung sigma(U_ij * x_j)
        sum_ax = np.dot(U[i, i+1:], x[i+1:])
        
        # Hitung x_i
        x[i] = (b_prime[i] - sum_ax) / U[i, i]
        print(f"Menghitung x[{i+1}]: {x[i]:.4f}")
        
    return x

# === MAIN PROGRAM ===

# Mendefinisikan matriks A dan vektor b dari masalah fisika
A = np.array([
    [5, -2, -3, 0],
    [-2, 11, 0, -5],
    [-3, 0, 8, -3],
    [0, -5, -3, 14]
])

b = np.array([20, 0, 10, 0])

# Panggil fungsi untuk menyelesaikan SPL
solusi = eliminasi_gauss(A, b)

print("\n=================== HASIL AKHIR ===================")
print("Solusi untuk arus (i1, i2, i3, i4) adalah:")
for i, val in enumerate(solusi):
    print(f"  i{i+1} = {val:.4f} Ampere")
print("===================================================")

# Verifikasi dengan solver bawaan numpy
print("\nVerifikasi hasil dengan np.linalg.solve():")
solusi_numpy = np.linalg.solve(A, b)
print(solusi_numpy)

### Kesimpulan

Masalah fisis mengenai analisis arus pada rangkaian listrik DC yang kompleks berhasil dimodelkan menjadi sebuah **sistem persamaan linear dengan empat variabel**. Sistem ini merepresentasikan hukum tegangan Kirchhoff untuk setiap loop pada rangkaian.

Dengan menerapkan **metode numerik Eliminasi Gauss**, sistem tersebut dapat diselesaikan secara efisien. Implementasi algoritma menggunakan Python berhasil menghitung nilai arus untuk setiap loop:

* Arus pada loop 1  = 5.3318 A
* Arus pada loop 2  = 1.3977 A
* Arus pada loop 3  = 2.8732 A
* Arus pada loop 4  = 0.8659 A

Studi kasus ini menunjukkan bahwa metode numerik merupakan alat yang sangat kuat untuk menyelesaikan masalah-masalah fisika-teknik yang dapat direpresentasikan secara matematis, dan hasilnya dapat diverifikasi secara akurat menggunakan perangkat lunak komputasi modern.

In [1]:
import numpy as np

def eliminasi_gauss(A, b):
    """
    Menyelesaikan sistem persamaan linear Ax = b menggunakan metode Eliminasi Gauss.

    Args:
        A (np.array): Matriks koefisien (n x n).
        b (np.array): Vektor konstanta (n x 1).

    Returns:
        np.array: Vektor solusi x.
    """
    n = len(b)
    # Buat augmented matrix [A|b] untuk kemudahan operasi
    Ab = np.hstack([A.astype(float), b.reshape(-1, 1).astype(float)])
    print("Matriks Augmented Awal [A|b]:")
    print(Ab)
    print("\n--- Proses Eliminasi Maju ---\n")

    # 1. Tahap Eliminasi Maju
    for j in range(n):
        # Cari baris dengan pivot terbesar (untuk stabilitas numerik)
        # Untuk kasus ini, kita asumsikan tidak perlu pivoting
        pivot_row = j
        
        # Lakukan eliminasi untuk baris di bawah pivot
        for i in range(j + 1, n):
            faktor = Ab[i, j] / Ab[j, j]
            Ab[i, j:] = Ab[i, j:] - faktor * Ab[j, j:]
            print(f"Operasi Baris R{i+1} = R{i+1} - ({faktor:.4f}) * R{j+1}")
            print(Ab)
            print("-" * 30)

    # Pisahkan kembali menjadi matriks U dan vektor b'
    U = Ab[:, :n]
    b_prime = Ab[:, n]

    print("\nMatriks Segitiga Atas (U):")
    print(U)
    print("\nVektor b' hasil modifikasi:")
    print(b_prime)
    print("\n--- Proses Substitusi Mundur ---\n")
    
    # 2. Tahap Substitusi Mundur
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        # Hitung sigma(U_ij * x_j)
        sum_ax = np.dot(U[i, i+1:], x[i+1:])
        
        # Hitung x_i
        x[i] = (b_prime[i] - sum_ax) / U[i, i]
        print(f"Menghitung x[{i+1}]: {x[i]:.4f}")
        
    return x

# === MAIN PROGRAM ===

# Mendefinisikan matriks A dan vektor b dari masalah fisika
A = np.array([
    [5, -2, -3, 0],
    [-2, 11, 0, -5],
    [-3, 0, 8, -3],
    [0, -5, -3, 14]
])

b = np.array([20, 0, 10, 0])

# Panggil fungsi untuk menyelesaikan SPL
solusi = eliminasi_gauss(A, b)

print("\n=================== HASIL AKHIR ===================")
print("Solusi untuk arus (i1, i2, i3, i4) adalah:")
for i, val in enumerate(solusi):
    print(f"  i{i+1} = {val:.4f} Ampere")
print("===================================================")

# Verifikasi dengan solver bawaan numpy
print("\nVerifikasi hasil dengan np.linalg.solve():")
solusi_numpy = np.linalg.solve(A, b)
print(solusi_numpy)

Matriks Augmented Awal [A|b]:
[[ 5. -2. -3.  0. 20.]
 [-2. 11.  0. -5.  0.]
 [-3.  0.  8. -3. 10.]
 [ 0. -5. -3. 14.  0.]]

--- Proses Eliminasi Maju ---

Operasi Baris R2 = R2 - (-0.4000) * R1
[[ 5.  -2.  -3.   0.  20. ]
 [ 0.  10.2 -1.2 -5.   8. ]
 [-3.   0.   8.  -3.  10. ]
 [ 0.  -5.  -3.  14.   0. ]]
------------------------------
Operasi Baris R3 = R3 - (-0.6000) * R1
[[ 5.  -2.  -3.   0.  20. ]
 [ 0.  10.2 -1.2 -5.   8. ]
 [ 0.  -1.2  6.2 -3.  22. ]
 [ 0.  -5.  -3.  14.   0. ]]
------------------------------
Operasi Baris R4 = R4 - (0.0000) * R1
[[ 5.  -2.  -3.   0.  20. ]
 [ 0.  10.2 -1.2 -5.   8. ]
 [ 0.  -1.2  6.2 -3.  22. ]
 [ 0.  -5.  -3.  14.   0. ]]
------------------------------
Operasi Baris R3 = R3 - (-0.1176) * R2
[[ 5.         -2.         -3.          0.         20.        ]
 [ 0.         10.2        -1.2        -5.          8.        ]
 [ 0.          0.          6.05882353 -3.58823529 22.94117647]
 [ 0.         -5.         -3.         14.          0.        ]]
-----